ARG version
FROM almalinux:${version:-8}
ARG course="Docker"
ARG trainer="NNR"
#ENV duration="12hrs"
ARG duration="120hrs"
ENV duration=${duration}

RUN echo "Couse is :${course} , trainer is ${trainer} , duration is ${duration}}"

CMD ["sleep","100"]