ARG version
FROM almalinux:${version:-8}
ARG course="Docker"
ARG trainer="NNR"
ENV duration="120hrs"

RUN echo "Couse is :${course} , trainer is ${trainer} , duration is ${duration}}"

CMD ["sleep","100"]